{% set version = "1.0" %}
{% set sha256 = "d4d8b82a39071fd202c89fe36a3aa2cad83ea2cfe8f30b592553636372555c75" %}


package:
  name: damageprofiler
  version: '{{version}}'

source:
  url: https://github.com/Integrative-Transcriptomics/DamageProfiler/releases/download/v{{ version }}/DamageProfiler-{{ version }}-java11.jar
  sha256: '{{sha256}}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk
    - python

test:
  commands:
    - damageprofiler -h  >/dev/null

about:
  home: https://github.com/Integrative-Transcriptomics/DamageProfiler
  license: GPL-3.0
  license_family: GPL
  summary: A Java based tool to determine damage patterns on ancient DNA as a replacement for mapDamage
