{% set version = "0.4.19" %}
{% set github = "https://github.com/acidgenomics/pipette" %}

package:
  name: r-pipette
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 1d453d092164af865b208e0c6c398acadb66456a78c08fd22a4e5690a10304de

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
      # Depends:
    - r-base
      # Imports:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-acidbase >=0.1.13
    - r-acidgenerics >=0.3.10
    - r-cli >=2.0
    - r-data.table >=1.12.8
    - r-goalie >=0.4.6
    - r-jsonlite >=1.7
    - r-matrix >=1.2
    - r-readr >=1.3.1
    - r-stringr >=1.4
    - r-syntactic >=0.4.2
    - r-tibble >=3.0.3
    - r-vroom >=1.2.1
    - r-yaml >=2.2.1
      # Suggests:
    - r-readxl >=1.3.1
    - r-rio >=0.5.16
  run:
      # Depends:
    - r-base
      # Imports:
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-rtracklayer
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-acidbase >=0.1.13
    - r-acidgenerics >=0.3.10
    - r-cli >=2.0
    - r-data.table >=1.12.8
    - r-goalie >=0.4.6
    - r-jsonlite >=1.7
    - r-matrix >=1.2
    - r-readr >=1.3.1
    - r-stringr >=1.4
    - r-syntactic >=0.4.2
    - r-tibble >=3.0.3
    - r-vroom >=1.2.1
    - r-yaml >=2.2.1
      # Suggests:
    - r-readxl >=1.3.1
    - r-rio >=0.5.16

test:
  commands:
    - $R -e "library('pipette')"

about:
  home: https://pipette.acidgenomics.com/
  dev_url: "{{ github }}"
  license: GPL-3.0-only
  license_file: LICENSE
  summary: Pipette biological data in and out of R.

extra:
  recipe-maintainers:
    - mjsteinbaugh
