 {% set version = "4.2.0" %}

package:
  name: cancerit-allelecount
  version: {{ version }}
source:
  url: https://github.com/cancerit/alleleCount/archive/v{{ version }}.tar.gz
  sha256: df5be9b4d2027f9228d59f4b9dbe7e416b8a5cf1bf4597418afb44662530142c
build:
  number: 0
  skip: True # [osx]
requirements:
  build:
    - {{ compiler('c') }}
    - htslib=1.9
  host:
    - zlib
    - wget
    - curl
    - bzip2
    - xz
    - libdeflate
    - htslib=1.9
  run:
    - zlib
    - htslib=1.9
test:
  commands:
    - 'alleleCounter -h'
about:
  home: https://github.com/cancerit/alleleCount
  license: GPLv3
  summary: Support code for NGS copy number algorithms
