 {% set version = "4.1.0" %}

package:
  name: cancerit-allelecount
  version: {{ version }}
source:
  url: https://github.com/cancerit/alleleCount/archive/v{{ version }}.tar.gz
  sha256: 19a2406257d116d5bc5882987bf66f75a137acc7e92bb80f5ae2f43f7e79b0b7
build:
  number: 0
  skip: True # [osx]
requirements:
  build:
    - {{ compiler('c') }}
    - htslib=1.9
  host:
    - zlib
    - wget
    - curl
    - bzip2
    - xz
    - libdeflate
    - htslib=1.9
  run:
    - zlib
    - htslib=1.9
test:
  commands:
    - 'alleleCounter -h'
about:
  home: https://github.com/cancerit/alleleCount
  license: GPLv3
  summary: Support code for NGS copy number algorithms
