{% set version = "1.2" %}
{% set name = "hitac" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

source:
  url: https://gitlab.com/dacs-hpi/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 08bb02f3549cc4eb0ab2842d6a05164d83ab2cd12725cc1b5691f6e21257b718

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - biopython
    - pandas
    - scikit-learn >=0.21.3
    - numpy >=1.13.3

test:
  commands:
    - hitac.py -h 2>&1 | grep "HiTaC"

about:
  home: https://gitlab.com/dacs-hpi/hitac
  license: 'GNU General Public License v3 (GPLv3)'
  license_file: LICENSE
  summary: 'A hierarchical taxonomy classifier for fungal ITS sequences'

extra:
  identifiers:
    - biotools:hitac
