{% set name = "constax" %}
{% set version = "2.0.2" %}
{% set sha256hash = "61f5e45af395d1f967559d4a7ce7ed02afbd6be4b78f946309a15fdb346680d3" %}
{% set md5hash = "9044f76d1c367e755c8125944a09656f" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

source:
  url: https://github.com/liberjul/CONSTAXv2/archive/v2.0.2.tar.gz
  sha256: {{ sha256hash }}
  md5: {{ md5hash }}

requirements:
  host:
  build:
    - python >=3.6
  run:
    - python >=3.6
    - rdptools
    - vsearch
    - blast
    - pandas
    - numpy

about:
  home: 'https://github.com/liberjul/CONSTAXv2'
  license: MIT

  summary: 'A software for accurate taxonomic classification of environmental DNA markers'
