{% set version = "0.4.3" %}
{% set github = "https://github.com/acidgenomics/syntactic" %}

package:
  name: r-syntactic
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: cc666fe9395878c23763c96dcb006bdf3cbbd256b658ff75265f45f1ebab6060

build:
  noarch: generic
  number: 0

requirements:
  host:
      # Depends:
    - r-base
      # Imports:
    - r-acidbase >=0.1.9
    - r-acidgenerics >=0.3.6
    - r-goalie >=0.4.4
    - r-stringi >=1.4.6
    - r-stringr >=1.4
  run:
      # Depends:
    - r-base
      # Imports:
    - r-acidbase >=0.1.9
    - r-acidgenerics >=0.3.6
    - r-goalie >=0.4.4
    - r-stringi >=1.4.6
    - r-stringr >=1.4

test:
  commands:
    - $R -e "library('syntactic')"

about:
  home: https://syntactic.acidgenomics.com/
  dev_url: "{{ github }}"
  license: GPL-3
  license_file: LICENSE
  summary: Make syntactically valid names out of character vectors.

extra:
  recipe-maintainers:
    - mjsteinbaugh
